### ISSUE TITLE
Identify address geocoding solution

### ISSUE THREAD

**Issue by wyseguy7** [internetofwater/ABOUT-US#5]
Users of the DroughtDashboard need to be able to determine which utility is providing their water, and this requires mapping a physical address to a geolocation (latitude/longitude coordinates). 

This task will be complete when we have identified a feasible geocoding solution. Tests will be run regarding the selection criteria below using a few sample addresses. If this solution costs money, we will ensure that these costs are acceptable with client. 

Selection criteria for a geocoding service will include:
1. How much does it cost per use? 
2. How sensitive is it to error (i.e. if I fat-finger my address, will it help me correct it?)
3. How fast/reliable is it? 
4. How correct is it?

**Comment by wyseguy7** [comment]
Spoke with Kyle, he indicated that he can provide land parcels if we'd like to press forward with a home-built solution

**Comment by wyseguy7** [comment]
Parcels are here https://www.nconemap.gov/pages/parcels

**Comment by ksonda** [comment]
[TAMU geocoder](http://geoservices.tamu.edu/Services/Geocode/WebService/) and [Census geocoder](https://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.html) are two maybe free options.
